[es]
  title = "The Data Is Flat"
  languageName = "[es]"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/es"
  
[en]
  title = "The Data Is Flat"
  languageName = "[en]"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/en"
