baseURL = "https://www.thedataisflat.com/"
languageCode = "es"
title = "TheDataIsFlat.com"
theme = "cactus"
copyright = "" # cactus will use title if copyright is not set
disqusShortname = "thedataisflat" # Used when comments is enabled. Cactus will use site title if not set
googleAnalytics = "G-SVEL7H3GGL"


# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "🏡 Home"
url = "/"
weight = 1

[[menu.main]]
name = "📝 Blog"
url = "/blog"
weight = 2

[[menu.main]]
name = "🌱 Garden"
url = "/garden"
weight = 3

[[menu.main]]
name = "ℹ️ About"
url = "/about"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]

  colortheme = "dark" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = false # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = true # default

  # Home page settings
  description = "Website of **`Javier Estraviz`**. Tech stuff and personal thoughts, mainly."
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/estraviz" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default

  [params.comments]
    enabled = true # default
    engine = "disqus" # only disqus, utterances, and cactus_comments is supported
    [params.comments.utterances]
      repo = "estraviz/blog-comments"
      label = "thedataisflat" # you can use however you want to label your name in your repo's issues
      theme = "github-dark"
    [params.comments.cactuscomments]
      siteName = "your_cactus_comments_sitename" # see https://cactus.chat/ on how to register your site name
      #serverUrl = "" # Defaults to https://matrix.cactus.chat:8448 (Cactus Chat public server)
      #serverName = "" # Defaults to cactus.chat

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/estraviz"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/javierestraviz/"
  [[params.social]]
    name = "email"
    link = "javier.estraviz+thedataisflat@gmail.com"
  [[params.social]]
    name = "twitter"
    link = "https://twitter.com/estraviz/"
  [[params.social]]
    name = "mastodon"
    link = "https://fosstodon.org/@estraviz"
